http:
  addr: ":8080"
  token: "a38b721f-e8c8-4cdf-95b0-baa13ee5ddd5"
dns:
  addr: ":53"
  net: "udp"
db:
  dsn: "file://app.json"
  #dsn: "sqlite3://./app.db"
  #dsn: mysql://root:root@tcp(localhost:3306)/app