http:
  addr: ":8080"
  token: "change-me"
dns:
  addr: ":53"
  net: "udp"
db:
  dsn: "file://app.json"
  #dsn: "sqlite3://./app.db"
  #dsn: mysql://root:root@tcp(localhost:3306)/app
log:
  level: "info"