name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: false

      - name: Cache Go Vendor Directory
        uses: actions/cache@v3
        id: vendor-cache
        with:
          path: vendor
          key: go-vendor-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-vendor-${{ runner.os }}-

      - name: Install Dependencies (if cache is missing)
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: |
          go mod tidy
          go mod vendor
          go mod verify

      - name: Run generate
        run: go generate ./...

      - name: Run tests
        run: go test ./...

      - name: Run static analysis
        run: go vet ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout=5m
