name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: false

      - name: Find changed Go files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.go$')
          echo "Changed Go files: $changed_files"
          echo "::set-output name=changed_files::$changed_files"

      - name: Cache Go Vendor Directory
        uses: actions/cache@v3
        id: vendor-cache
        with:
          path: vendor
          key: go-vendor-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-vendor-${{ runner.os }}-

      - name: Install Dependencies (if cache is missing)
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: |
          go mod tidy
          go mod vendor
          go mod verify

      - name: Run generate
        run: go generate ./...

      - name: Run static analysis on changed files
        run: |
          # If there are changed Go files, run go vet on them
          if [ -n "${{ steps.changed-files.outputs.changed_files }}" ]; then
            echo "Running go vet on changed files..."
            go vet ${{ steps.changed-files.outputs.changed_files }}
          else
            echo "No Go files changed, skipping go vet."
          fi

      - name: Run golangci-lint on changed files
        run: |
          # If there are changed Go files, run golangci-lint on them
          if [ -n "${{ steps.changed-files.outputs.changed_files }}" ]; then
            echo "Running golangci-lint on changed files..."
            go run github.com/golangci/golangci-lint/cmd/golangci-lint run ${{ steps.changed-files.outputs.changed_files }} --timeout=5m
          else
            echo "No Go files changed, skipping golangci-lint."
          fi

      - name: Run tests
        run: go test ./...