name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
          cache: false

      - name: Get changed Go files
        id: changed-files
        run: |
          changed_files=$(git diff --name-only --diff-filter=ACMR HEAD^ HEAD | grep '\.go$' | tr '\n' ',' | sed 's/,$//')
          changed_dirs=$(git diff --name-only --diff-filter=ACMR HEAD^ HEAD | grep '\.go$' | xargs -n1 dirname | sort -u | tr '\n' ',' | sed 's/,$//')
          
          echo "changed_files=${changed_files}" >> $GITHUB_OUTPUT
          echo "changed_dirs=${changed_dirs}" >> $GITHUB_OUTPUT

      - name: Cache Go Vendor Directory
        uses: actions/cache@v3
        id: vendor-cache
        with:
          path: vendor
          key: go-vendor-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            go-vendor-${{ runner.os }}-

      - name: Install Dependencies (if cache is missing)
        if: steps.vendor-cache.outputs.cache-hit != 'true'
        run: |
          go mod tidy
          go mod vendor
          go mod verify

      - name: Run generate
        run: go generate ./...

      - name: Run static analysis on changed files
        if: steps.changed-files.outputs.files_count != '0'
        run: |
          packages=$(echo "${{ steps.changed-files.outputs.changed_files }}" | xargs -n1 dirname | sort -u)
          echo "Running go vet on packages: $packages"
          for pkg in $packages; do
            go vet ./$pkg
          done

      - name: Run lint analysis of the modified files directories
        if: steps.changed-files.outputs.files_count != '0'
        uses: golangci/golangci-lint-action@v7
        with:
          args: --path-prefix=${{ steps.changed-files.outputs.changed_dirs }} --skip-dirs-use-default

      - name: Run tests
        run: go test ./...